version: "3"
services: 
  jupyter-lab:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    image: tensorflow/tensorflow:2.11.0rc1-gpu-jupyter
    ports:  
      - "8889:8889"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PASSWORD=vt2mssih
      - JUPYTER_TOKEN=mcc2024
    volumes:
      - ./tf-knugs:/tf-knugs
   # devices:
   #   - /dev/video0:/dev/video0